server:
  port: 8080
app:
  timeToLive: -1 # '-1' for turning expiry off; otherwise, should be at least '1' (minute)
db:
  types:
    main: 'sequelize' # options: 'sequelize;'
    queue: 'redis' # options: 'redis;'
  redis:
    port: 6379
  sequelize:
    host: 'localhost'
    user: 'root'
    password: '7895leon' # INSERT PASSWORD HERE
    db: 'clinic'
    dialect: 'mysql'
security:
  jwt_secret: 'itrex-lab-test-test-test-test-test-test-test'
  jwt_expiry: '90d'
  jwt_cookie_expiresIn: 90 # days
